### ISSUE TITLE
控制台中发现 3 处错误和 1 处警告

### ISSUE THREAD

**Issue by MinonHeart** [wjywbs/chrome-newtab-reloaded#18]
Chrome 版本：40.0.2214.91 (正式版本) m
在新 Tab 中审查元素发现控制台中有 3 处错误和 1 处警告，导致 Chrome 的 Tab 一直处于加载状态，左上角的刷新按钮一直处于 × 号的状态。

**Comment by wjywbs** [comment]
测试发现Chrome 40确实有这个问题，之前没注意到刷新按钮。3 处错误是正常现象，但那个警告导致了浏览器一直处于加载状态："Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/." 看起来像是浏览器本身的问题，显示警告也不应该保持加载状态。

只是把这个地方改成异步的会导致2个线程运行顺序不同，有时显示空白页。再想想好办法。
