### ISSUE TITLE
The Chrome team is planning on axing the hidden NTP features brought back by your extension

### ISSUE THREAD

**Issue by nothinglastsforever** [wjywbs/chrome-newtab-reloaded#20]
Hi Jingyi,

I thought I should bring this to your attention as this will break your much loved extension:
https://code.google.com/p/chromium/issues/detail?id=329637#c5

>#5 dbeam@chromium.org
>I think these things are always hidden or don't exist anymore and can be axed:
>1) recently closed menu
>2) other sessions menu
>3) most visited page
>4) the upper right "login container"

I've already responded in their thread as protest, and am trying to inform as many others as possible.

Kind Regards

Christopher

**Comment by wjywbs** [comment]
Thank you very much for notifying me. After looking at the changes, I find that this extension will not be affected because we have a local copy of the old NTP code. This extension depends on the new NTP features, which is the one with the Google logo and search bar. Please tell me when Google starts to delete or modify the new NTP code.

**Comment by wjywbs** [comment]
i will reopen this issue when there might be a breaking change in chrome.
