### ISSUE TITLE
No longer working on Chrome 50

### ISSUE THREAD

**Issue by egret85** [wjywbs/chrome-newtab-reloaded#26]
New tab page is no longer being replaced on Chrome Version 50.0.2661.102 m on Windows 8.1.

**Comment by egret85** [comment]
Chrome now loading new tab page from chrome-search://local-ntp/local-ntp.html and not from a web address.

**Comment by wjywbs** [comment]
This is very likely a Chrome bug that can not be controlled by this extension. Usually it's caused by intermittent connection to google when opening the new tab page. If you see "NTP Request Interceptor" in the network tab of "inspect elements" when you refresh the new tab page, then it's a bug.

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/search/new_tab_page_interceptor_service.cc&sq=package:chromium&type=cs&l=81

**Comment by egret85** [comment]
Ok, It has started working again.  Weird that I could get to google just fine when it wasn't working, but it kept loading the local NTP.
